{ config, pkgs, ... }:

{
  # Powerlevel10k 配置文件
  home.file.".p10k.zsh" = {
    text = ''
      # Generated by Powerlevel10k configuration wizard
      "builtin" "local" "-a" "p10k_config_opts"
      [[ ! -o "aliases"         ]] || p10k_config_opts+=("aliases")
      [[ ! -o "sh_glob"         ]] || p10k_config_opts+=("sh_glob")
      [[ ! -o "no_brace_expand" ]] || p10k_config_opts+=("no_brace_expand")
      "builtin" "setopt" "no_aliases" "no_sh_glob" "brace_expand"

      () {
        emulate -L zsh -o extended_glob

        # 主要外观设置
        typeset -g POWERLEVEL10K_MODE=nerdfont-complete
        typeset -g POWERLEVEL10K_ICON_PADDING=none
        typeset -g POWERLEVEL10K_ICON_BEFORE_CONTENT=
        
        # 提示符类型
        typeset -g POWERLEVEL10K_PROMPT_ADD_NEWLINE=true
        typeset -g POWERLEVEL10K_TRANSIENT_PROMPT=off
        typeset -g POWERLEVEL10K_INSTANT_PROMPT=verbose
        
        # 左右提示符
        typeset -g POWERLEVEL10K_LEFT_PROMPT_ELEMENTS=(
          dir
          vcs
          status
        )
        
        typeset -g POWERLEVEL10K_RIGHT_PROMPT_ELEMENTS=(
          time
        )
        
        # 目录设置
        typeset -g POWERLEVEL10K_DIR_BACKGROUND=4
        typeset -g POWERLEVEL10K_DIR_FOREGROUND=0
        # 完整路径显示
        typeset -g POWERLEVEL10K_SHORTEN_STRATEGY=none
        typeset -g POWERLEVEL10K_DIR_PATH_SEPARATOR=/
        
        # VCS 设置
        typeset -g POWERLEVEL10K_VCS_CLEAN_BACKGROUND=2
        typeset -g POWERLEVEL10K_VCS_MODIFIED_BACKGROUND=3
        typeset -g POWERLEVEL10K_VCS_UNTRACKED_BACKGROUND=2
        typeset -g POWERLEVEL10K_VCS_CONFLICTED_BACKGROUND=3
        typeset -g POWERLEVEL10K_VCS_LOADING_BACKGROUND=8
        
        # 状态指示器
        typeset -g POWERLEVEL10K_STATUS_OK=false
        typeset -g POWERLEVEL10K_STATUS_ERROR=true
        typeset -g POWERLEVEL10K_STATUS_ERROR_BACKGROUND=1
        typeset -g POWERLEVEL10K_STATUS_ERROR_FOREGROUND=0
        
        # 时间格式
        typeset -g POWERLEVEL10K_TIME_FORMAT=%D{%H:%M}
        
        # 即时提示设置
        typeset -g POWERLEVEL10K_INSTANT_PROMPT=verbose
        
        # 禁用特定段的图标
        typeset -g POWERLEVEL10K_HOME_ICON=
        typeset -g POWERLEVEL10K_HOME_SUB_ICON=
        typeset -g POWERLEVEL10K_FOLDER_ICON=
        
        # 禁用主机名显示
        typeset -g POWERLEVEL10K_CONTEXT_TEMPLATE=
        typeset -g POWERLEVEL10K_CONTEXT_PREFIX=
        typeset -g POWERLEVEL10K_CONTEXT_SUFFIX=
        
        # 额外添加以下配置来确保完全禁用主机名
        typeset -g POWERLEVEL10K_HOST_TEMPLATE=
        typeset -g POWERLEVEL10K_USERNAME_TEMPLATE=
        
        # 完成配置
        (( ! p10k_config_opts[*] )) || setopt $p10k_config_opts[*]
        'builtin' 'unset' 'p10k_config_opts'
      }
    '';
    force = true;
  };

  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    enableCompletion = true;
    syntaxHighlighting.enable = true;
    
    plugins = [
      {
        name = "powerlevel10k";
        src = pkgs.zsh-powerlevel10k;
        file = "share/zsh-powerlevel10k/powerlevel10k.zsh-theme";
      }
    ];
    
    # oh-my-zsh 配置
    oh-my-zsh = {
      enable = true;
      plugins = [];
    };
    
    # 自定义别名
    shellAliases = {
      # 压缩文件相关
      gz = "tar -xzvf";
      tgz = "tar -xzvf";
      bz2 = "tar -xjvf";
      
      # 应用程序快捷方式
      mate = "open -a 'TextMate'";
      crm = "open -a 'Google Chrome'";
      webstorm = "open -a 'WebStorm'";
      idea = "open -a 'IntelliJ IDEA'";
      markdown = "open -a 'Typora'";
      code = "open -a 'Visual Studio Code'";
      
      # 其他
      his = "history";
      ll = "ls -alh";
      la = "ls -a";
      vim = "nvim";
      
      # Tree 相关
      t = "tree -L 1";
      t2 = "tree -L 2";
      t3 = "tree -L 3";
      
      # Python 相关
      pv = "python -m venv .venv";
      
      # System
      zz = "source ~/.zshrc";  # Quick reload of zsh config
      
      # Wave 相关别名
      wv = "wsh view";
      we = "wsh edit";
      ww = "wsh web open";
      wsv = "wsh setvar";
      wr = "wsh run";
      wrx = "wsh run -x";
      wm = "wsh getmeta";
      wa = "wsh ai";
      
      # 常用应用程序别名
      c = "cursor";
      v = "nvim";
      p = "python";
      
      # 系统监控相关别名
      top = "htop";  # 使用 htop 替代 top
      btm = "bottom";  # bottom 的快捷方式
      df = "duf";  # 更好的磁盘使用分析
      ps = "procs";  # 更现代的进程查看
      gl = "glances";  # glances 快捷方式
      
      # 快速查看系统信息
      cpu = "htop -s PERCENT_CPU";  # CPU 使用率排序
      mem = "htop -s PERCENT_MEM";  # 内存使用率排序
      disk = "duf";  # 磁盘使用情况
      sys = "glances";  # 系统概览
    };
    
    # 初始化脚本
    initExtra = ''
      # ZSH 历史记录配置
      HISTFILE="$HOME/.zsh_history"
      HISTSIZE=50000
      SAVEHIST=50000
      
      # Zoxide 初始化
      eval "$(zoxide init zsh)"
      
      # 历史记录选项
      setopt EXTENDED_HISTORY
      setopt HIST_IGNORE_ALL_DUPS
      setopt HIST_SAVE_NO_DUPS
      setopt HIST_REDUCE_BLANKS
      setopt HIST_VERIFY
      setopt SHARE_HISTORY
      unsetopt BANG_HIST
      
      # Conda 初始化
      __conda_setup="$(~/anaconda3/bin/conda 'shell.zsh' 'hook' 2> /dev/null)"
      if [ $? -eq 0 ]; then
          eval "$__conda_setup"
      else
          if [ -f "~/anaconda3/etc/profile.d/conda.sh" ]; then
              . "~/anaconda3/etc/profile.d/conda.sh"
          else
              export PATH="~/anaconda3/bin:$PATH"
          fi
      fi
      unset __conda_setup
      
      # Powerlevel10k 配置
      if [[ -r "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
        source "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
      fi

      # NVM 配置
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      
      # 快捷键设置
      bindkey -e
      bindkey '\e\e[C' forward-word
      bindkey '\e\e[D' backward-word
      
      # 其他自定义配置
      setopt AUTO_CD
      setopt CORRECT
    '';
  };
} 